services:
  lzcustom-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lzcustom-frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend/public/assets:/app/public/assets
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://lzcustom-backend:8000
    restart: unless-stopped
    networks:
      - web-network

  lzcustom-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lzcustom-backend
    ports:
      - "8001:8000"
    volumes:
      - ./database:/app/database
    environment:
      - PYTHONPATH=/app
      - DATABASE_PATH=/app/database/lz_custom.db
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped
    depends_on:
      - ollama
    networks:
      - web-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - web-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:3000"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - lzcustom-frontend
      - lzcustom-backend
    restart: unless-stopped
    networks:
      - web-network

volumes:
  ollama-data:

networks:
  web-network:
    driver: bridge
