version: '3.8'

services:
  # Main Web Application
  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      - ./static:/app/static
      - ./uploads:/app/uploads
      - ./database:/app/database
    environment:
      - FLASK_ENV=production
      - AI_ENABLED=true
      - AI_MODEL=deepseek
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OLLAMA_ENDPOINT=http://localhost:11434
      - DATABASE_URL=sqlite:///database/lz_custom.db
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
    network_mode: host

# Using host Ollama - no volumes needed
