version: '3.8'

services:
  # Main Mail Server (Postfix + Dovecot)
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.giorgiy.org
    env_file: mailserver.env
    ports:
      - "25:25"     # SMTP
      - "143:143"   # IMAP
      - "465:465"   # SMTPS
      - "587:587"   # Submission
      - "993:993"   # IMAPS
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    stop_grace_period: 1m
    healthcheck:
      test: "ss -lntp | grep -E ':25|:143|:465|:587|:993' || exit 1"
      timeout: 45s
      interval: 30s
      retries: 3
      start_period: 90s
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.mail.unix.max_dgram_qlen=50
    networks:
      - mail-network

  # Roundcube Webmail
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    depends_on:
      - mailserver
      - roundcube-db
    ports:
      - "8080:80"
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=roundcube-db
      - ROUNDCUBEMAIL_DB_USER=roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube_password
      - ROUNDCUBEMAIL_DB_NAME=roundcube
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mailserver
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mailserver
      - ROUNDCUBEMAIL_SMTP_PORT=587
    volumes:
      - roundcube-data:/var/www/html
    restart: unless-stopped
    networks:
      - mail-network

  # Database for Roundcube
  roundcube-db:
    image: mysql:8.0
    container_name: roundcube-db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=roundcube
      - MYSQL_USER=roundcube
      - MYSQL_PASSWORD=roundcube_password
    volumes:
      - roundcube-db-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - mail-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: mail-redis
    restart: unless-stopped
    networks:
      - mail-network

  # Fail2Ban for security
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./docker-data/fail2ban:/data
      - /var/log:/var/log:ro
    environment:
      - TZ=America/New_York
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=30d
    restart: unless-stopped

volumes:
  roundcube-data:
  roundcube-db-data:

networks:
  mail-network:
    driver: bridge
