version: '3.8'

# VPS Dime Tier 1 (1GB RAM) - Basic Website + External AI
# Features: Static website, contact forms, external AI API
# Price: $3-5/month

services:
  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VPS_TIER=tier1
      - API_URL=http://backend:8000
    volumes:
      - ./nginx/tier1.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend.tier1
    environment:
      - VPS_TIER=tier1
      - DATABASE_URL=sqlite:///app/lz_custom.db
      - EXTERNAL_AI_PROVIDER=openai
      - EXTERNAL_AI_KEY=${OPENAI_API_KEY}
      - AI_USAGE_LIMIT=50  # Daily limit
    volumes:
      - ../backend:/app
      - tier1_data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.5

volumes:
  tier1_data:

networks:
  default:
    driver: bridge