name: Build and deploy Python app to Azure Web App - LZCustom

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Clean up for deployment
        run: |
          # Remove unnecessary files
          rm -rf venv/
          rm -rf .git/
          rm -rf azure-app-service/
          rm -rf backend/node_modules/
          rm -rf frontend/node_modules/

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_LZCUSTOM }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'LZCustom'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_LZCUSTOM }}
          package: .
